# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qv < Formula
  desc "A CLI tool for quick variable management"
  homepage "https://github.com/shivgitcode/qv"
  version "2.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shivgitcode/qv/releases/download/v2.0.2/qv_2.0.2_darwin_amd64.tar.gz"
      sha256 "baa0aa84562aeb6e982a07ebe85a10a5ee4a0c1b526f62abff99f9779d0a3116"

      def install
        bin.install "qv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shivgitcode/qv/releases/download/v2.0.2/qv_2.0.2_darwin_arm64.tar.gz"
      sha256 "bf41450e59e2343f0ee4759f500e295f2ea7770e8cbb343dddc87e7c6992ffb0"

      def install
        bin.install "qv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/shivgitcode/qv/releases/download/v2.0.2/qv_2.0.2_linux_amd64.tar.gz"
      sha256 "1975f1bfec4f0be9dd8146a01163810d43b2b614ac3d61f6594e306d839ac416"
      def install
        bin.install "qv"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shivgitcode/qv/releases/download/v2.0.2/qv_2.0.2_linux_arm64.tar.gz"
      sha256 "03e9a2e2462d7d6d22385a1d1eb8f4cc7b6d57df7fd854147645d2b5eac6e250"
      def install
        bin.install "qv"
      end
    end
  end

  test do
    system "#{bin}/qv", "list"
  end
end
