# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qv < Formula
  desc "A CLI tool for quick variable management"
  homepage "https://github.com/shivgitcode/qv"
  version "2.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shivgitcode/qv/releases/download/v2.0.4/qv_2.0.4_darwin_amd64.tar.gz"
      sha256 "1aaefa97c24eb873818c9db12726d90322840eff42449c22d6c575a088600406"

      def install
        bin.install "qv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shivgitcode/qv/releases/download/v2.0.4/qv_2.0.4_darwin_arm64.tar.gz"
      sha256 "757197ef06e68b9683d89b2511b551e2b5a6897ef40f9257f5241ecc389cd6c0"

      def install
        bin.install "qv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/shivgitcode/qv/releases/download/v2.0.4/qv_2.0.4_linux_amd64.tar.gz"
      sha256 "f5414f989d2406ed29cdf5b382dbcba3b789a8281aaeb2abfbfa524e8fffcf8b"
      def install
        bin.install "qv"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shivgitcode/qv/releases/download/v2.0.4/qv_2.0.4_linux_arm64.tar.gz"
      sha256 "cb7d08b8018ddea735c8ff91ee728a4e7838ac6598dcb430cd95a885a6fffafd"
      def install
        bin.install "qv"
      end
    end
  end

  test do
    system "#{bin}/qv"
  end
end
